### ISSUE TITLE
No play torrents iOS  can download Torrents 

### ISSUE THREAD

**Issue by Doctor2023** [b-movie/bee-desktop#3]
does not play torrents in version ios apple b.movie and I can not download Torrents iOS

**Comment by an-lee** [comment]
You mean it can not play torrent in your iPhone browser. Yes, it does not support doing that. You have to use the desktop client to play torrent, at least for now.

**Comment by Doctor2023** [comment]
but at some point it will work for ios or only for mac window is that I have an ipad pro I can not play the torrents on my ipad pro I can only play on my mac pro not on the ipad pro I think it could be a player to play the torrents from ipad pro and ben ios it may be that at some point it will be compatible for ios and ipoas pro play torrents from the tablet download

**Comment by an-lee** [comment]
> but at some point it will work for ios or only for mac window is that I have an ipad pro I can not play the torrents on my ipad pro I can only play on my mac pro not on the ipad pro I think it could be a player to play the torrents from ipad pro and ben ios it may be that at some point it will be compatible for ios and ipad pro play torrents from the tablet download

The torrent feature does not work in browser, no matter in you iPhone, iPad or Macbook. In browser, it will pop up a modal to alert you that to use desktop client if you click on any magnet source(torrent). But the stream sources in `CineStream` can play in browser.

I hope I've make clear.

**Comment by Doctor2023** [comment]
![IMG_0653](https://github.com/b-movie/bee-desktop/assets/129991276/6a8fcbd6-1af7-4551-8123-f9701aae0d7a)

The Cinestream links do not appear in some movies and series at some point some Cinestream alternatives can be added for b.movie page

**Comment by an-lee** [comment]
> The Cinestream links do not appear in some movies and series at some point some Cinestream alternatives can be added for b.movie page

Yes. Cinestream is offline these days. I'm looking for alternatives.
