### ISSUE TITLE
please implement  to b.movie

### ISSUE THREAD

**Issue by Doctor2023** [b-movie/bee-desktop#5]
![Screenshot_20230616-162942_Stremio](https://github.com/b-movie/bee-desktop/assets/129991276/d6430c11-a755-463c-8e89-c9610b75ce02)
![Screenshot_20230616-163101_Stremio](https://github.com/b-movie/bee-desktop/assets/129991276/13a97d86-2ec0-4732-b3ed-5a21a6d74995)
![Screenshot_20230616-163031_Stremio](https://github.com/b-movie/bee-desktop/assets/129991276/87730a88-eb04-4b26-bcea-0e857f0d838a)
![Screenshot_20230616-163143_Stremio](https://github.com/b-movie/bee-desktop/assets/129991276/4e875e9d-02a5-4ddf-99d2-0e7c3f8ab715)
![Screenshot_20230616-163311_Stremio](https://github.com/b-movie/bee-desktop/assets/129991276/31a48eb5-12ee-4448-8719-1e8ff72fffea)
![Screenshot_20230616-163348_Stremio](https://github.com/b-movie/bee-desktop/assets/129991276/04d6fd16-b259-404b-a110-ba9748d74587)

I am are similar to CineStream to see if it can be implemented

These are images from another application but there are the names so you can implement b.movie

I hope it has helped you to see more content

**Comment by an-lee** [comment]
Thx. I'll check them all.

**Comment by Doctor2023** [comment]
> Thx. I'll check them all.

ok friend thanks you

**Comment by an-lee** [comment]
User can install add-on now.

![image](https://github.com/b-movie/bee-desktop/assets/22209056/ff56354f-5b47-43fc-857b-87b24ac01537)
