### ISSUE TITLE
Please implement airplay to b.movie

### ISSUE THREAD

**Issue by Doctor2023** [b-movie/bee-desktop#6]
Please implement add airplay

**Comment by an-lee** [comment]
coming soon.

**Comment by Doctor2023** [comment]
> coming soon.

ok friend thanks you

**Comment by Doctor2023** [comment]
when does version 4.3 of b.movie come out friend

**Comment by an-lee** [comment]
Here you go https://github.com/b-movie/bee-desktop/releases/tag/v0.4.3
