### ISSUE TITLE
 error  javaScript  airplay to b.movie

### ISSUE THREAD

**Issue by Doctor2023** [b-movie/bee-desktop#7]
![20230621_222506](https://github.com/b-movie/bee-desktop/assets/129991276/ba60761e-21d1-4e60-a584-ed73e1afd648)

I get this error when playing videos torrents and movies and series with airplay apple tv

**Comment by an-lee** [comment]
Sorry for that. I've never tested the airplay feature since I don't have an Apple TV. Luckily I'll have one soon. I'll test it and fix it ASSP.

**Comment by an-lee** [comment]
> Sorry for that. I've never tested the airplay feature since I don't have an Apple TV. Luckily I'll have one soon. I'll test it and fix it ASSP.

Unfortunately, implementing airplay in Electron App seems to be a difficult issue, at least for now. After days of trying, I have to remove the airplay feature for now.

related: https://github.com/webtorrent/webtorrent-desktop/issues/1339
