### ISSUE TITLE
version 0.5.0  airplay working apple tv b.movie

### ISSUE THREAD

**Issue by Doctor2023** [b-movie/bee-desktop#9]
when will version 0.5.0 come out friend

**Comment by Doctor2023** [comment]
will be fixed to play airplay with apple tv with version 0.5.0 b.movie

**Comment by an-lee** [comment]
Unfortunately, implementing airplay in Electron App seems to be a difficult issue, at least for now. After days of trying, I have to remove the airplay feature for now.

related: https://github.com/webtorrent/webtorrent-desktop/issues/1339
